apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: mapping-datastore
  namespace: openshift-mtv
spec:
  map:
    - destination:
        storageClass: ocs-storagecluster-ceph-rbd
      source:
        id: datastore-48
  provider:
    destination:
      name: host
      namespace: openshift-mtv
    source:
      name: vmware
      namespace: openshift-mtv

