kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: vddk-build
  namespace: vmexamples
spec:
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'vddk:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'tools:latest'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: >
      FROM registry.access.redhat.com/ubi8/ubi-minimal

      RUN curl -L -O
      www.opentlc.com/download/ocp4_baremetal/VMware-vix-disklib-7.0.3-20134304.x86_64.tar.gz

      RUN tar -xzf VMware-vix-disklib-7.0.3-20134304.x86_64.tar.gz

      RUN mkdir -p /opt

      ENTRYPOINT ["cp", "-r", "/vmware-vix-disklib-distrib", "/opt"]
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vddk
  namespace: vmexamples
spec:
  lookupPolicy:
    local: false

