apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
metadata:
  name: vmware
  namespace: openshift-mtv
spec:
  secret:
    name: vmware-credentials
    namespace: openshift-mtv
  settings:
    vddkInitImage: 'image-registry.openshift-image-registry.svc:5000/openshift/vddk:latest'
  type: vsphere
  url: 'https://portal.vc.opentlc.com/sdk'