apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet1-network
spec:
  config: |
    {
            "cniVersion": "0.3.1", 
            "name": "localnet1", 
            "type": "ovn-k8s-cni-overlay", 
            "topology": "localnet", 
            "netAttachDefName": "vmexamples/localnet1-network" 
    }
