apiVersion: 'kubevirt.io/v1'
kind: 'VirtualMachine'
metadata:
  annotations:
    vm.kubevirt.io/validations: "[\n  {\n    \"name\": \"minimal-required-memory\",\n    \"path\": \"jsonpath::.spec.domain.memory.guest\",\n    \"rule\": \"integer\",\n    \"message\": \"This VM requires more memory.\",\n    \"min\": 1073741824\n  }\n]\n"
  labels:
    app: 'ubuntu-vm'
    kubevirt.io/dynamic-credentials-support: 'true'
  name: 'ubuntu-vm'
spec:
  dataVolumeTemplates:
    - apiVersion: 'cdi.kubevirt.io/v1beta1'
      kind: 'DataVolume'
      metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        creationTimestamp: null
        name: 'ubuntu-vm'
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: '30Gi'
    - metadata:
        creationTimestamp: null
        name: 'ubuntu-vm-installation-cdrom'
      spec:
        source:
          http:
            url: 'https://mirror.easyname.at/ubuntu-releases/24.04/ubuntu-24.04-live-server-amd64.iso'
        storage:
          resources:
            requests:
              storage: '30Gi'
  running: false
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: 'small'
        vm.kubevirt.io/os: 'ubuntu'
        vm.kubevirt.io/workload: 'server'
      creationTimestamp: null
      labels:
        kubevirt.io/domain: 'ubuntu-vm'
        kubevirt.io/size: 'small'
    spec:
      architecture: 'amd64'
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 2
              disk:
                bus: 'virtio'
              name: 'rootdisk'
            - bootOrder: 3
              disk:
                bus: 'virtio'
              name: 'cloudinitdisk'
            - bootOrder: 4
              cdrom:
                bus: 'sata'
              name: 'installation-cdrom'
          interfaces:
            - macAddress: '02:43:c4:00:00:0a'
              masquerade: {}
              model: 'virtio'
              name: 'default'
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: 'pc-q35-rhel9.2.0'
        memory:
          guest: '2Gi'
        resources: {}
      networks:
        - name: 'default'
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: 'ubuntu-vm'
          name: 'rootdisk'
        - cloudInitNoCloud:
            userData: "#cloud-config\nuser: fedora\npassword: 8l3w-3jk4-itjo\nchpasswd: { expire: False }"
          name: 'cloudinitdisk'
        - dataVolume:
            name: 'ubuntu-vm-installation-cdrom'
          name: 'installation-cdrom'
