apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: flatnetwork
  namespace: vmexamples
spec:
  config: >-
    {"name":"flatnetwork","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br-flat","macspoofchk":true,"ipam":{}}
