---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: server-deployer
spec:
  tasks:
    - name: modify-data-object
      params:
        - name: manifest
          value: |
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              generateName: fedora-server-
            spec:
              pvc:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
                volumeMode: Filesystem
              # source:
              #  registry:
              #    url: docker://registry.redhat.io/rhel9/rhel-guest-image:9.2
              #    pullMethod: node                
              source:
                http:
                  url: https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/38/Cloud/x86_64/images/Fedora-Cloud-Base-38-1.6.x86_64.raw.xz
              # sourceRef:
              #   kind: DataSource
              #   name: fedora
              #   namespace: openshift-virtualization-os-images
        - name: waitForSuccess
          value: 'true'
      taskRef:
        kind: Task
        name: modify-data-object
    - name: generate-ssh-keys
      params:
        - name: privateKeyConnectionOptions
          value:
            - 'user:fedora'
            - 'disable-strict-host-key-checking:true'
      taskRef:
        kind: Task
        name: generate-ssh-keys
    - name: disk-virt-customize
      params:
        - name: pvc
          value: "$(tasks.modify-data-object.results.name)"
        - name: customizeCommands
          value: |
            # install httpd
            # run-command systemctl enable httpd.service 
            # run-command systemctl start httpd.service
            # install git,vim,pip
            # run-command pip install flask
            run-command ls
      taskRef:
        kind: Task
        name: disk-virt-customize
      runAfter:
        - modify-data-object
    - name: create-vm-from-manifest
      params:
        - name: manifest
          value: |
            apiVersion: kubevirt.io/v1
            kind: VirtualMachine
            metadata:
              generateName: fedora-vm-
              annotation:
                description: Fedora 38 VM generated by server-deployer pipeline
              labels:
                app: fedora-vm
            spec:
              running: true
              template:
                metadata:
                  labels:
                    kubevirt.io/domain: fedora-vm
                spec:
                  accessCredentials:
                    - sshPublicKey:
                        source:
                          secret:
                            secretName: $(tasks.generate-ssh-keys.results.publicKeySecretName)
                        propagationMethod:
                          configDrive: {}
                  domain:
                    cpu:
                      cores: 2
                      sockets: 1
                      threads: 1
                    devices:
                      disks:
                        - name: rootdisk
                          bootOrder: 1
                          disk:
                            bus: virtio
                        - name: cloudinitdrive
                          disk:
                            bus: virtio
                      interfaces:
                        - bridge: {}
                          name: default
                      networkInterfaceMultiqueue: true
                      rng: {}
                    resources:
                      requests:
                        memory: 2Gi
                  hostname: fedora-vm
                  networks:
                    - name: default
                      pod: {}
                  volumes:
                    - dataVolume:
                        name: "$(tasks.modify-data-object.results.name)"
                      name: rootdisk
                    - name: cloudinitdrive
                      cloudInitConfigDrive:
                        userData: |
                          #cloud-config
                          password: fedora
                          chpasswd: { expire: False }
        - name: ownDataVolumes
          value:
            - "rootdisk:$(tasks.modify-data-object.results.name)"
      runAfter:
        - disk-virt-customize
        - generate-ssh-keys
      taskRef:
        kind: Task
        name: create-vm-from-manifest
    - name: execute-in-vm
      params:
        - name: vmName
          value: $(tasks.create-vm-from-manifest.results.name)
        - name: secretName
          value: $(tasks.generate-ssh-keys.results.privateKeySecretName)
        - name: script
          value: |
            echo 'This is a demo created by server-deployer-pipeline :)' > /var/www/html/index.html
      runAfter:
        - create-vm-from-manifest
      taskRef:
        kind: Task
        name: execute-in-vm